Create database QuanLyThietbiTrongTruong
go
use QuanLyThietbiTrongTruong
go 
-- 1
CREATE TABLE NhanVien
(
maNV VARCHAR(10) NOT NULL PRIMARY KEY,
tenNV NVARCHAR(50) NOT NULL,
ngaySinh DATE NULL,
gioiTinh BIT NULL,
sdt VARCHAR(13) NULL,
diaChi VARCHAR NULL,
tenDangNhap VARCHAR NULL,
matkhau VARCHAR NULL,
);


-- 2

CREATE TABLE ChucVu
(
maCV VARCHAR(10) NOT NULL PRIMARY KEY,
tenCV NVARCHAR(50) NULL,
);

--3

CREATE TABLE ChucVu_NhanVien
(
maCV VARCHAR(10) NOT NULL,
maNV VARCHAR(10) NOT NULL,
soChucVuDamNhiem INT NULL DEFAULT 1,
	PRIMARY KEY (maCV,maNV),
	CONSTRAINT FK_CVNV_CV FOREIGN KEY (maCV) REFERENCES ChucVu(maCV)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE ,
	CONSTRAINT FK_CVNV_NV FOREIGN KEY (maNV) REFERENCES NhanVien(maNV)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE 
);
 

 -- 4

CREATE TABLE ViTri
(
maVT VARCHAR(5) NOT NULL PRIMARY KEY,
tenVT NVARCHAR(50) NULL ,
dienTich FLOAT NULL,
);

-- 5

CREATE TABLE Thanhli
(
maTL VARCHAR(10) NOT NULL PRIMARY KEY,
ngayTL DATE NULL,
);

--6

CREATE TABLE NhaSanXuat
(
maNSX VARCHAR(10) NOT NULL PRIMARY KEY,
tenNSX NVARCHAR(100) NULL ,
);

--7

CREATE TABLE ThietBi
(
maTB VARCHAR(10) NOT NULL PRIMARY KEY,
tenTB VARCHAR(100) NULL,
maLoaiTB VARCHAR(100) NULL,
maNSX VARCHAR(10) NOT NULL,
ngaySX DATE NULL,
gia FLOAT NULL,
CONSTRAINT FK_TB_NSX FOREIGN KEY (maNSX) REFERENCES NhaSanXuat(maNSX)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE
);

--8

CREATE TABLE Phong
(
maPhong VARCHAR(10) NOT NULL PRIMARY KEY,
tenPhong NVARCHAR(100) NULL ,
maVT VARCHAR(5) NOT NULL,
CONSTRAINT FK_Phong_VT FOREIGN KEY (maVT) REFERENCES ViTri(maVT)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE
);

--9

CREATE TABLE Phong_ThietBi
(
maPhong VARCHAR(10) NOT NULL,
maTB VARCHAR(10) NOT NULL ,
soLuong INT NULL,
ghiChu VARCHAR(100) NULL,
PRIMARY KEY(maPhong, maTB),
CONSTRAINT FK_Phong_TB_Phong FOREIGN KEY (maPhong) REFERENCES Phong(maPhong)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE,
CONSTRAINT FK_Phong_TB_TB FOREIGN KEY (maTB) REFERENCES ThietBi(maTB)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE
);

--10

CREATE TABLE ThanhLi_ThietBi
(
maTB VARCHAR(10) NOT NULL ,
maTL VARCHAR(10) NOT NULL ,
soLuong INT NULL,
donGia FLOAT NULL,
PRIMARY KEY(maTL, maTB),
CONSTRAINT FK_TL_TB_TL FOREIGN KEY (maTL) REFERENCES ThanhLi(maTL)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE,
CONSTRAINT FK_TL_TB_TB FOREIGN KEY (maTB) REFERENCES ThietBi(maTB)
	ON DELETE 
		CASCADE
	ON UPDATE
		CASCADE
);
